terraform-ecs-fargate-service/service.tf, terraform-ecs-fargate-service/variables.tf
`figure-backend` má specifický `unhealthy_threshold` (https://github.com/FigurePOS/figure-backend/blob/ecb5d82268ded4a28db910578aef0d9f4b568985/tf/ecs_fargate_service/service.tf#L56), tak bych ty thresholdy parametrizoval raději rovnou oba.
=> feat: parametrize elb health check thresholds FGR3-2163

terraform-ecs-fargate-service/service.tf
Potřebuju exposnout arn target groupy load balanceru, protože `make-it-butter-api` má [jednu custom rule navíc](https://github.com/FigurePOS/make-it-butter-api/blob/0b82ca2303f0c8b0b128d530fe6dc0f1febcec5b/tf/ecs_fargate_service/service.tf#L87-L105), tak ta arn je potřeba k tomu aby ji šlo dodefinovat.
=> feat: output elb target group arn FGR3-2163

CODEOWNERS, terraform-ecs-fargate-autoscaling-basic/autoscaling.tf
viz. <img width="1411" alt="CleanShot 2023-08-28 at 10 07 54@2x" src="https://github.com/FigurePOS/terraform-modules/assets/215660/d4f887ac-4466-4ea5-9339-30a19f6dcef9">
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_target.html
=> fix: ignore tags changes on aws_appautoscaling_target FGR3-2228

terraform-datadog-sqs/main.tf, terraform-datadog-sqs/variables.tf
Přidal jsem monitor, který zavolá OpsGenie pokud nárůst zpráv v DLQ za posledních pět minut přesáhne 20, jak jsme se bavili. 
Původní monitor na celkový počet zpráv jsem nechal s tím, že jen píše do Slacku. Rád bych to upravil tak, že vytvoří DD incident který bude low-prio a assignuje se odpovídajícímu týmu. Ale vypadá to, že v DD jdou snad incidenty zakládat jen manuálně v UI nebo ze Slacku. 🤔 To je divný, ale nechci tím teď ztrácet čas, napsal jsem na to issue.
`locked` property je deprekovaná, místo ní je tam ta `restricted_roles` s referencí na id admin role přes `data`.
=> feat: add dd monitor for increased messages in dead letter queue FGR3-2572

terraform-datadog-sqs/main.tf, terraform-datadog-sqs/variables.tf
Myslím že ten warning na total number of messages (tj. ten co se neposílá do Opsgenie) můžeme úplně oddělat? Navíc je tam problém s tou default nulou že se nebere jako undefined ale opravdu jako nula:
=> fix: remove warning from total number of DLQ messages FGR3-2572

README.md, terraform-datadog-ecs-service/main.tf, terraform-datadog-ecs-service/variables.tf, terraform-datadog-metric-slo/main.tf, terraform-datadog-metric-slo/variables.tf, terraform-datadog-slo-event-handler/main.tf, terraform-datadog-slo-event-handler/variables.tf, terraform-datadog-slo-express-endpoint/main.tf, terraform-datadog-slo-express-endpoint/variables.tf, terraform-datadog-slo-graphql-endpoint/main.tf, terraform-datadog-slo-graphql-endpoint/variables.tf, terraform-datadog-sqs/main.tf, terraform-datadog-sqs/variables.tf, terraform-ecs-fargate-autoscaling-basic/autoscaling.tf, terraform-ecs-fargate-autoscaling-basic/variables.tf, terraform-ecs-fargate-service/service.tf, terraform-ecs-fargate-service/variables.tf
Jediný dvě změny je nahrazení deprekované `locked` property za `restricted_roles` a odstranění "readable" service names. Zbytek změn jsou jen whitespaces po aplikaci `terraform format`.
Začal jsem to upravovat, protože chci upravit ty čtyři moduly na SLOčka (ty `terraform-datadog-slo-*` se dají přepsat aby reusovaly `terraform-datadog-metric-slo` a neduplikovaly kód), ale pošlu to až jako další PR.
=> refactor: tf format + remove obsolete locked property + do not use _readable_ service names FGR3-2585

terraform-datadog-monitor-express-endpoint/main.tf, terraform-datadog-monitor-express-endpoint/variables.tf
Jsem se moc nechal unést při tom [odstraňování readable service names](https://github.com/FigurePOS/terraform-modules/pull/12/files). Resource name by mohl zůstat v readable verzi:
=> fix: return readable resource name in express monitor FGR3-2585

terraform-ecs-fargate-autoscaling-basic/variables.tf, terraform-ecs-fargate-service/data.tf, terraform-ecs-fargate-service/service.tf, terraform-ecs-fargate-service/variables.tf
Hlavně kvůli Javě musím trochu změnit definici entry pointu. Když bude zadaná var `entry_point`, tak se použije, když ne a bude zadaná `entry_point_node_script`, tak se před ni přidá `exec node --enable-source-maps` a pokud nebude zadaná ani jedna, tak zůstane entry point prázdný.
=> fix(task): entry point + simplify input variables  FGR3-2215

.circleci/config.yml, terraform-ecs-fargate-service/service.tf
Do tý `PATH_PREFIX` env proměnný se nedává service name ale např. `/message-router` (a možná ani nebude potřeba všude), tak bych to raději nastavoval per service. 
A k tomu jsem přidal tagy. Nastavují se sice v každý servise přes default tagy (např. https://github.com/FigurePOS/fgr-message-router/blob/dc8922d717032eb61fb317a2fb671d7c83d6b4e9/tf/general.tf#L25-L30), ale když to tam nedám, tak to v plánu dělá takovejhle zbytečnej bordel (zřejmě bug toho aws modulu):
=> fix: remove path_prefix env var from ecs task + add tags FGR3-2215

terraform-ecs-fargate-service/ecs_task.tf, terraform-ecs-fargate-service/execution_role.tf, terraform-ecs-fargate-service/task_role.tf, terraform-ecs-fargate-service/variables.tf
Popsal jsem to víc v tomhle PR kde jsem to zkoušel: https://github.com/FigurePOS/node-template/pull/53#issuecomment-1945751222
- Přidal jsem do modulu task roli i execution roli
- Povolil jsem na tasku [volat exec](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-exec.html#ecs-exec-enabling-and-using)
- Přidal jsem health check na datadog kontejner
=> feat: add iam roles to ecs-task module FGR3-2215

terraform-ecs-fargate-service/data.tf, terraform-ecs-fargate-service/ecs_task.tf, terraform-ecs-fargate-service/execution_role.tf, terraform-ecs-fargate-service/task_role.tf
Tak přece jen ještě jedno doplnění. 🙂 Každý ecs task má log groupu, ta se taky nemusí definovat v každým repu.
=> feat: add log group to ecs-task module and use unified task permissions FGR3-2215

terraform-ecs-fargate-service/ecs.tf
Tohle ještě zbytečně zavazí v terraform plánu:
=> fix: add empty systemControls to ecs task definition FGR3-3975

ecs-autoscaling-cpu/outputs.tf
Použiju to v Java backendu, kde na ty policies navěsím CloudWatch alarmy na memory:
https://github.com/FigurePOS/figure-backend/pull/698/files#diff-d2280c42a749f3cd2bf829b9eb66e2a30e0821652c7d1c7564aa5cc0e0827f1c
=> feat: output autoscaling policy arns FGR3-4279

ecs-service/ecs.tf, ecs-service/variables.tf
Přišla mi vhodná chvíle ušetřit pár dolarů. 😅 A je to docela rychlá věc, kterou bysme mohli vyzkoušet třeba na jedný servise.
- `base` je počet instancí, který se mají pro danýho capacity providera pustit vždycky - default je `1` pro `reserved` instance.
- `weight` je poměr instancí. Default je `100` reserved a `0` spot.
V produkci např. u Business Config API máme 3-10 tasků. Pokud bychom chtěli být konzervativní, tak můžeme na začátek zkusit třeba 2:1 reserved:spot, tak by to vypadalo takto:
```
{
reserved = {
base   = 2
weight = 2
}
spot  = {
base   = 1
weight = 1
}
}
```
Dev by se vlastně asi na spotech mohl pustit celý. 🤔 🙂
=> feat: settings for ECS capacity providers to allow running spot instances FGR3-4880

ecs-service/ecs.tf
Nový deployment chceme stejně vždycky a bez toho se snaží replacovat celou servisu při změně nastavení spotů:
=> fix: set force_new_deployment for ecs task FGR3-5031

datadog-sqs/datadog_monitor.tf, datadog-sqs/variables.tf
paymenty notifikují navíc ještě do `#alerts-payments`, tak přidávám volitelný parametr
=> feat(datadog-sqs): allow optional message for total messages monitor FGR3-5150

aws-ecs-autoscaling/policy.tf, aws-ecs-autoscaling/variables.tf
Lokálně na Auth service to vypadá dobře, ale chtělo by to pořádně otestovat, ale vůbec nevím jak. 😅 
Default na ty zprávy jsem jenom střelil, jsem otevřenej nápadům, vůbec netuším, kolik jich tam tak bývá obecně. Další možnost je ten argument udělat bez defaultu a ať si to každej, kdo to používá vymyslí po svým.
Další věc je ještě, že mě nenapadlo, jak to udělat volitelný, aby sis mohl vybrat, jestli to chceš používat na té service nebo ne. Další modul jsem dělat nechtěl a jediný, co mě napadlo je ten default hodit přestřelenej, takže se k němu nikdy nepřiblížíme a rádoby to nebude fungovat.
=> feat: introduce sqs utilization metric to autoscaling FGR3-5364

aws-ecs-autoscaling/policy.tf
Zkusil jsem to na devu java backendu a prošlo to. 🤷‍♂️ Nevím teda jestli to je opravdu důvod toho zvýšenýho počtu tasků, ale imho tímhle nic nezkazíme. 😅
=> fix(autoscaling): use built-in ECSServiceAverageMemoryUtilization metric

aws-lambda-function/build.sh
Ta původní syntax je bashová, ale celý skript pouštím jako posix shell, protože se nechci spolíhat na bash.
=> fix: lambda build

aws-lambda-function/lambda.tf
V cestě na s3 nemůže být commit hash, jinak se bude triggerovat replace při každým mergi.
=> fix: s3 path for lambda build

aws-lambda-function/build.sh
Jen odstraní zbytečný outputy z npm install a pro jistotu manuálně vytvoří build folder.
=> fix: improve lambda build

aws-dynamodb-table/main.tf, aws-ecs-autoscaling/main.tf, aws-ecs-service/main.tf, aws-ecs-task-definition/main.tf, aws-lambda-function/main.tf, aws-s3-bucket/main.tf, aws-sqs-queue/main.tf
Vyšel aws provider v6 a zřejmě je safe upgradnout, ale na druhou stranu asi není dobrý dovolat automaticky upgrade na další major verzi.
=> feat: allow aws provider v6
